# قائمة أسهم ثابتة مرشحة (Small-Cap / Penny Stocks)
# تستخدم كـ fallback فقط لو فشل Finnhub بجلب قائمة السوق الكاملة

SYMBOL_POOL = [
    "NIO", "XPEV", "LI", "NKLA", "WKHS", "RIDE", "GOEV", "FSR", "MULN",
    "PLUG", "FCEL", "BLDP", "CLNE", "HYLN", "SOLO", "AYRO", "ARVL",
    "BLNK", "CHPT", "EVGO", "LEV", "PTRA", "REE", "XL", "AMPX",
    "QS", "FREY", "ENVX", "SES", "MVST", "ASTS", "VLDR", "LIDR", "OUST",
    "MARA", "RIOT", "BTBT", "HUT", "BITF", "CAN", "SOS", "EBON", "GREE",
    "CLSK", "CIFR", "CORZ", "SDIG", "DGHI", "IREN", "WULF", "ARBK",
    "BTCS", "BTCM", "ANY", "COIN", "MSTR", "BKKT", "OSTK",
    "ZCMD", "YRD", "BIYA", "AZTR", "FCUV", "TIGR", "FUTU", "IQ", "BILI",
    "JMIA", "CPNG", "GRAB", "DIDI", "TME", "VIPS", "YMM", "NTES",
    "DOYU", "HUYA", "WB", "SOHU", "MOMO", "FINV", "QFIN", "TAL",
    "EDU", "GOTU", "LX", "UP", "RERE", "DADA", "ZTO", "BEST",
    "TLRY", "CGC", "ACB", "HEXO", "OGI", "CRON", "SNDL", "GRWG",
    "CURLF", "TCNNF", "CRLBF", "AYR", "VFF",
    "OCGN", "INO", "VXRT", "NVAX", "SRNE", "ATOS", "CTXR", "PHUN",
    "TTOO", "AEZS", "SESN", "IMGN", "AGEN", "ADMA", "CYCC", "ADXS",
    "BCLI", "VBIV", "OBSV", "AVXL", "PGEN", "TNXP", "AXSM", "CYTK",
    "SGMO", "RGNX", "FOLD", "ARDX", "CDTX", "CYTH", "ENTA", "GERN",
    "IMRA", "KPTI", "MNKD", "NBIX", "OCUL", "PBYI", "RIGL", "SAVA",
    "TGTX", "VRNA", "XBIT", "ZYNE", "APTO", "BIOC", "CDXC", "DRRX",
    "BBBY", "EXPR", "KOSS", "NOK", "BB", "AMC", "GME", "PROG", "BBIG",
    "ATER", "CENN", "SPRT", "IRNT", "OPAD", "DWAC", "COSM", "COEP",
    "MMTLP", "MMAT", "ANVS", "WISH", "SKLZ", "CLOV", "OPEN",
    "CTRM", "TOPS", "SHIP", "GLBS", "GOGL", "SBLK", "EGLE", "SB",
    "DAC", "SSW", "GRIN", "PANL", "NM", "NMM",
    "IDEX", "APDN", "XELA", "REEA", "GSAT", "SIEB", "CIDM", "WKEY",
    "AMPE", "ASRT", "MARK", "GEVO", "AEHR", "AEYE", "AGRX", "AMST",
    "APPS", "AUID", "BTAI", "CEVA", "DTIL", "EVLV", "FUBO", "GOEV",
    "IONQ", "LAZR", "MVIS", "PLBY", "SATS", "SPWR", "VUZI", "WKSP",
    "SIRI", "SOFI", "PLTR", "ASTR", "DNA", "JOBY", "ACHR", "LILM",
    "EVTL", "BLDE", "RSKD", "LOTZ", "IRNT", "TMC", "HYZN", "GOEV",
    "USEG", "REI", "SPRC", "VTNR", "CPE", "CEI", "AMPY", "GTE",
    "HUSA", "SBOW", "VTOL", "NOG", "MGY", "CRK",
    "ENVB", "APRN", "NILE", "SABR", "MMAT", "ANY", "AYRO", "XSPA",
    "PRTY", "PRTS", "BODY", "CTSO", "DPW", "ELMS", "FUV", "GBOX",
    "HOFV", "INDO", "JAGX", "KOPN", "LGVN", "MIST", "NAK", "NUZE",
    "ONTX", "PAVM", "QUBT", "RCAT", "SLNO", "TRVN", "UPH", "VERB",
    "WEED", "XERS", "YGMZ", "ZDGE", "ADAP", "BFRI", "CLRB", "DLPN",
    "NVOS", "OBLG", "PAVS", "QNRX", "RDBX", "SILO", "TENX", "UONE",
    "VINC", "WORX", "XTLB", "YJ", "ZKIN", "ALPP", "BNGO", "CREG",
]
